// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 22/9/2568 04:55:38
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.js";
const config = [
{"content":{"files":["C:/Users/ithean/OneDrive/เดสก์ท็อป/งาน/kanban-board/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ithean/OneDrive/เดสก์ท็อป/งาน/kanban-board/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ithean/OneDrive/เดสก์ท็อป/งาน/kanban-board/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ithean/OneDrive/เดสก์ท็อป/งาน/kanban-board/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ithean/OneDrive/เดสก์ท็อป/งาน/kanban-board/plugins/**/*.{js,ts,mjs}","C:/Users/ithean/OneDrive/เดสก์ท็อป/งาน/kanban-board/composables/**/*.{js,ts,mjs}","C:/Users/ithean/OneDrive/เดสก์ท็อป/งาน/kanban-board/utils/**/*.{js,ts,mjs}","C:/Users/ithean/OneDrive/เดสก์ท็อป/งาน/kanban-board/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ithean/OneDrive/เดสก์ท็อป/งาน/kanban-board/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ithean/OneDrive/เดสก์ท็อป/งาน/kanban-board/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/ithean/OneDrive/เดสก์ท็อป/งาน/kanban-board/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;